package interfaceSampler;

import java.awt.Color;
import java.io.*;
import java.util.HashMap;
import javax.swing.*;
import javax.sound.sampled.*;

public class SamplerInterface extends javax.swing.JFrame {

    int xMouse, yMouse;
    private File audioFile; // Para almacenar el archivo de audio seleccionado
    private Clip audioClip; // Para controlar la reproducción

    private File[] audioFiles; // Array para almacenar el archivo de audio de cada pad
    private Clip[] audioClips; // Array para controlar la reproducción de cada pad
    private static final int NUMBER_OF_PADS = 6; // Número de pads
    private HashMap<String, File[]> perfilAudios; 

    public SamplerInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("BeatLab");

        ImageIcon icon = new ImageIcon(getClass().getResource(""));
        setIconImage(icon.getImage());

        // Inicializa arrays para los archivos y clips de cada pad
        audioFiles = new File[NUMBER_OF_PADS];
        audioClips = new Clip[NUMBER_OF_PADS];
        
        perfilAudios = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        panelTextoReestablecer = new interfaceSampler.PanelRound();
        label_TextoReestablecer = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        beatlabLabel = new javax.swing.JLabel();
        iconBeatLab = new javax.swing.JLabel();
        panelCerrarPantalla = new javax.swing.JPanel();
        cerrarPestañaTXT = new javax.swing.JLabel();
        panelMinimizar = new javax.swing.JPanel();
        minimizarTXT = new javax.swing.JLabel();
        panelPADS = new javax.swing.JPanel();
        estructuraPanel1 = new javax.swing.JPanel();
        asignarSonidoPanel1 = new javax.swing.JPanel();
        asignarSonidoTxt101 = new javax.swing.JLabel();
        numeroDelPadPanel1 = new javax.swing.JPanel();
        numeroDelPad101 = new javax.swing.JLabel();
        pad1 = new javax.swing.JPanel();
        estructuraPanel2 = new javax.swing.JPanel();
        asignarSonidoPanel2 = new javax.swing.JPanel();
        asignarSonidoTxt102 = new javax.swing.JLabel();
        numeroDelPadPanel2 = new javax.swing.JPanel();
        numeroDelPad102 = new javax.swing.JLabel();
        pad2 = new javax.swing.JPanel();
        estructuraPanel3 = new javax.swing.JPanel();
        asignarSonidoPanel30 = new javax.swing.JPanel();
        asignarSonidoTxt103 = new javax.swing.JLabel();
        numeroDelPadPanel3 = new javax.swing.JPanel();
        numeroDelPad103 = new javax.swing.JLabel();
        pad3 = new javax.swing.JPanel();
        estructuraPanel4 = new javax.swing.JPanel();
        asignarSonidoPanel4 = new javax.swing.JPanel();
        asignarSonidoTxt104 = new javax.swing.JLabel();
        numeroDelPadPanel4 = new javax.swing.JPanel();
        numeroDelPad104 = new javax.swing.JLabel();
        pad4 = new javax.swing.JPanel();
        estructuraPanel50 = new javax.swing.JPanel();
        asignarSonidoPanel50 = new javax.swing.JPanel();
        asignarSonidoTxt105 = new javax.swing.JLabel();
        numeroDelPadPanel5 = new javax.swing.JPanel();
        numeroDelPad105 = new javax.swing.JLabel();
        pad5 = new javax.swing.JPanel();
        estructuraPanel60 = new javax.swing.JPanel();
        asignarSonidoPanel60 = new javax.swing.JPanel();
        asignarSonidoTxt106 = new javax.swing.JLabel();
        numeroDelPadPanel6 = new javax.swing.JPanel();
        numeroDelPad106 = new javax.swing.JLabel();
        pad6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(19, 19, 19));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 30, 920, 10));

        panelTextoReestablecer.setBackground(new java.awt.Color(31, 31, 31));
        panelTextoReestablecer.setRoundBottomLeft(30);
        panelTextoReestablecer.setRoundBottomRight(30);
        panelTextoReestablecer.setRoundTopLeft(30);
        panelTextoReestablecer.setRoundTopRight(30);

        label_TextoReestablecer.setBackground(new java.awt.Color(210, 210, 210));
        label_TextoReestablecer.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        label_TextoReestablecer.setForeground(new java.awt.Color(230, 230, 230));
        label_TextoReestablecer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_TextoReestablecer.setText("<html>Guardar los sonidos de los pads en el perfil seleccionado.<html>");

        javax.swing.GroupLayout panelTextoReestablecerLayout = new javax.swing.GroupLayout(panelTextoReestablecer);
        panelTextoReestablecer.setLayout(panelTextoReestablecerLayout);
        panelTextoReestablecerLayout.setHorizontalGroup(
            panelTextoReestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoReestablecerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_TextoReestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTextoReestablecerLayout.setVerticalGroup(
            panelTextoReestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoReestablecerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_TextoReestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(panelTextoReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 160, 80));

        header.setBackground(new java.awt.Color(0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        beatlabLabel.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        beatlabLabel.setForeground(new java.awt.Color(255, 255, 255));
        beatlabLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beatlabLabel.setText("BeatLab");

        iconBeatLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beatLogoRedimensionado.png"))); // NOI18N
        iconBeatLab.setText("jLabel4");

        panelCerrarPantalla.setBackground(new java.awt.Color(0, 0, 0));
        panelCerrarPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCerrarPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCerrarPantallaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrarPantallaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrarPantallaMouseExited(evt);
            }
        });

        cerrarPestañaTXT.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cerrarPestañaTXT.setForeground(new java.awt.Color(255, 255, 255));
        cerrarPestañaTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarPestañaTXT.setText("x");
        cerrarPestañaTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarPestañaTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarPestañaTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarPestañaTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarPestañaTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarPantallaLayout = new javax.swing.GroupLayout(panelCerrarPantalla);
        panelCerrarPantalla.setLayout(panelCerrarPantallaLayout);
        panelCerrarPantallaLayout.setHorizontalGroup(
            panelCerrarPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarPantallaLayout.createSequentialGroup()
                .addComponent(cerrarPestañaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        panelCerrarPantallaLayout.setVerticalGroup(
            panelCerrarPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarPestañaTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelMinimizar.setBackground(new java.awt.Color(0, 0, 0));

        minimizarTXT.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        minimizarTXT.setForeground(new java.awt.Color(255, 255, 255));
        minimizarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizarTXT.setText("-");
        minimizarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMinimizarLayout = new javax.swing.GroupLayout(panelMinimizar);
        panelMinimizar.setLayout(panelMinimizarLayout);
        panelMinimizarLayout.setHorizontalGroup(
            panelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizarTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        panelMinimizarLayout.setVerticalGroup(
            panelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinimizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(iconBeatLab, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beatlabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 662, Short.MAX_VALUE)
                .addComponent(panelCerrarPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(793, 793, 793)
                    .addComponent(panelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(panelCerrarPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(iconBeatLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beatlabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(panelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 40));

        panelPADS.setBackground(new java.awt.Color(10, 10, 10));

        estructuraPanel1.setBackground(new java.awt.Color(10, 10, 10));

        asignarSonidoPanel1.setBackground(new java.awt.Color(51, 51, 51));
        asignarSonidoPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));

        asignarSonidoTxt101.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        asignarSonidoTxt101.setForeground(new java.awt.Color(255, 255, 255));
        asignarSonidoTxt101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignarSonidoTxt101.setText("Asignar");
        asignarSonidoTxt101.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignarSonidoTxt101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt101MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt101MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt101MouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarSonidoPanel1Layout = new javax.swing.GroupLayout(asignarSonidoPanel1);
        asignarSonidoPanel1.setLayout(asignarSonidoPanel1Layout);
        asignarSonidoPanel1Layout.setHorizontalGroup(
            asignarSonidoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        asignarSonidoPanel1Layout.setVerticalGroup(
            asignarSonidoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        numeroDelPadPanel1.setBackground(new java.awt.Color(10, 10, 10));

        numeroDelPad101.setBackground(new java.awt.Color(10, 10, 10));
        numeroDelPad101.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        numeroDelPad101.setForeground(new java.awt.Color(255, 255, 255));
        numeroDelPad101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDelPad101.setText("PAD 1");

        javax.swing.GroupLayout numeroDelPadPanel1Layout = new javax.swing.GroupLayout(numeroDelPadPanel1);
        numeroDelPadPanel1.setLayout(numeroDelPadPanel1Layout);
        numeroDelPadPanel1Layout.setHorizontalGroup(
            numeroDelPadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        numeroDelPadPanel1Layout.setVerticalGroup(
            numeroDelPadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pad1.setBackground(new java.awt.Color(51, 51, 51));
        pad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        pad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pad1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pad1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pad1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pad1Layout = new javax.swing.GroupLayout(pad1);
        pad1.setLayout(pad1Layout);
        pad1Layout.setHorizontalGroup(
            pad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pad1Layout.setVerticalGroup(
            pad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estructuraPanel1Layout = new javax.swing.GroupLayout(estructuraPanel1);
        estructuraPanel1.setLayout(estructuraPanel1Layout);
        estructuraPanel1Layout.setHorizontalGroup(
            estructuraPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numeroDelPadPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        estructuraPanel1Layout.setVerticalGroup(
            estructuraPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel1Layout.createSequentialGroup()
                .addComponent(asignarSonidoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDelPadPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        estructuraPanel2.setBackground(new java.awt.Color(10, 10, 10));

        asignarSonidoPanel2.setBackground(new java.awt.Color(51, 51, 51));
        asignarSonidoPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        asignarSonidoPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        asignarSonidoTxt102.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        asignarSonidoTxt102.setForeground(new java.awt.Color(255, 255, 255));
        asignarSonidoTxt102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignarSonidoTxt102.setText("Asignar");
        asignarSonidoTxt102.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignarSonidoTxt102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt102MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt102MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt102MouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarSonidoPanel2Layout = new javax.swing.GroupLayout(asignarSonidoPanel2);
        asignarSonidoPanel2.setLayout(asignarSonidoPanel2Layout);
        asignarSonidoPanel2Layout.setHorizontalGroup(
            asignarSonidoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        asignarSonidoPanel2Layout.setVerticalGroup(
            asignarSonidoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        numeroDelPadPanel2.setBackground(new java.awt.Color(10, 10, 10));

        numeroDelPad102.setBackground(new java.awt.Color(10, 10, 10));
        numeroDelPad102.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        numeroDelPad102.setForeground(new java.awt.Color(255, 255, 255));
        numeroDelPad102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDelPad102.setText("PAD 2");

        javax.swing.GroupLayout numeroDelPadPanel2Layout = new javax.swing.GroupLayout(numeroDelPadPanel2);
        numeroDelPadPanel2.setLayout(numeroDelPadPanel2Layout);
        numeroDelPadPanel2Layout.setHorizontalGroup(
            numeroDelPadPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        numeroDelPadPanel2Layout.setVerticalGroup(
            numeroDelPadPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pad2.setBackground(new java.awt.Color(51, 51, 51));
        pad2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        pad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pad2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pad2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pad2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pad2Layout = new javax.swing.GroupLayout(pad2);
        pad2.setLayout(pad2Layout);
        pad2Layout.setHorizontalGroup(
            pad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pad2Layout.setVerticalGroup(
            pad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estructuraPanel2Layout = new javax.swing.GroupLayout(estructuraPanel2);
        estructuraPanel2.setLayout(estructuraPanel2Layout);
        estructuraPanel2Layout.setHorizontalGroup(
            estructuraPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numeroDelPadPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        estructuraPanel2Layout.setVerticalGroup(
            estructuraPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel2Layout.createSequentialGroup()
                .addComponent(asignarSonidoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDelPadPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        estructuraPanel3.setBackground(new java.awt.Color(10, 10, 10));

        asignarSonidoPanel30.setBackground(new java.awt.Color(51, 51, 51));
        asignarSonidoPanel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));

        asignarSonidoTxt103.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        asignarSonidoTxt103.setForeground(new java.awt.Color(255, 255, 255));
        asignarSonidoTxt103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignarSonidoTxt103.setText("Asignar");
        asignarSonidoTxt103.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignarSonidoTxt103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt103MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt103MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt103MouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarSonidoPanel30Layout = new javax.swing.GroupLayout(asignarSonidoPanel30);
        asignarSonidoPanel30.setLayout(asignarSonidoPanel30Layout);
        asignarSonidoPanel30Layout.setHorizontalGroup(
            asignarSonidoPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asignarSonidoPanel30Layout.setVerticalGroup(
            asignarSonidoPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        numeroDelPadPanel3.setBackground(new java.awt.Color(10, 10, 10));

        numeroDelPad103.setBackground(new java.awt.Color(10, 10, 10));
        numeroDelPad103.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        numeroDelPad103.setForeground(new java.awt.Color(255, 255, 255));
        numeroDelPad103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDelPad103.setText("PAD 3");

        javax.swing.GroupLayout numeroDelPadPanel3Layout = new javax.swing.GroupLayout(numeroDelPadPanel3);
        numeroDelPadPanel3.setLayout(numeroDelPadPanel3Layout);
        numeroDelPadPanel3Layout.setHorizontalGroup(
            numeroDelPadPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        numeroDelPadPanel3Layout.setVerticalGroup(
            numeroDelPadPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pad3.setBackground(new java.awt.Color(51, 51, 51));
        pad3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        pad3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pad3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pad3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pad3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pad3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pad3Layout = new javax.swing.GroupLayout(pad3);
        pad3.setLayout(pad3Layout);
        pad3Layout.setHorizontalGroup(
            pad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        pad3Layout.setVerticalGroup(
            pad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estructuraPanel3Layout = new javax.swing.GroupLayout(estructuraPanel3);
        estructuraPanel3.setLayout(estructuraPanel3Layout);
        estructuraPanel3Layout.setHorizontalGroup(
            estructuraPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numeroDelPadPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        estructuraPanel3Layout.setVerticalGroup(
            estructuraPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel3Layout.createSequentialGroup()
                .addComponent(asignarSonidoPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pad3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDelPadPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        estructuraPanel4.setBackground(new java.awt.Color(10, 10, 10));

        asignarSonidoPanel4.setBackground(new java.awt.Color(51, 51, 51));
        asignarSonidoPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));

        asignarSonidoTxt104.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        asignarSonidoTxt104.setForeground(new java.awt.Color(255, 255, 255));
        asignarSonidoTxt104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignarSonidoTxt104.setText("Asignar");
        asignarSonidoTxt104.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignarSonidoTxt104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt104MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt104MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt104MouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarSonidoPanel4Layout = new javax.swing.GroupLayout(asignarSonidoPanel4);
        asignarSonidoPanel4.setLayout(asignarSonidoPanel4Layout);
        asignarSonidoPanel4Layout.setHorizontalGroup(
            asignarSonidoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt104, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asignarSonidoPanel4Layout.setVerticalGroup(
            asignarSonidoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt104, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        numeroDelPadPanel4.setBackground(new java.awt.Color(10, 10, 10));

        numeroDelPad104.setBackground(new java.awt.Color(10, 10, 10));
        numeroDelPad104.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        numeroDelPad104.setForeground(new java.awt.Color(255, 255, 255));
        numeroDelPad104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDelPad104.setText("PAD 4");

        javax.swing.GroupLayout numeroDelPadPanel4Layout = new javax.swing.GroupLayout(numeroDelPadPanel4);
        numeroDelPadPanel4.setLayout(numeroDelPadPanel4Layout);
        numeroDelPadPanel4Layout.setHorizontalGroup(
            numeroDelPadPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad104, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        numeroDelPadPanel4Layout.setVerticalGroup(
            numeroDelPadPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad104, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pad4.setBackground(new java.awt.Color(51, 51, 51));
        pad4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        pad4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pad4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pad4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pad4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pad4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pad4Layout = new javax.swing.GroupLayout(pad4);
        pad4.setLayout(pad4Layout);
        pad4Layout.setHorizontalGroup(
            pad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pad4Layout.setVerticalGroup(
            pad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estructuraPanel4Layout = new javax.swing.GroupLayout(estructuraPanel4);
        estructuraPanel4.setLayout(estructuraPanel4Layout);
        estructuraPanel4Layout.setHorizontalGroup(
            estructuraPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numeroDelPadPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pad4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        estructuraPanel4Layout.setVerticalGroup(
            estructuraPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel4Layout.createSequentialGroup()
                .addComponent(asignarSonidoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pad4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDelPadPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        estructuraPanel50.setBackground(new java.awt.Color(10, 10, 10));

        asignarSonidoPanel50.setBackground(new java.awt.Color(51, 51, 51));
        asignarSonidoPanel50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));

        asignarSonidoTxt105.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        asignarSonidoTxt105.setForeground(new java.awt.Color(255, 255, 255));
        asignarSonidoTxt105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignarSonidoTxt105.setText("Asignar");
        asignarSonidoTxt105.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignarSonidoTxt105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt105MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt105MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt105MouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarSonidoPanel50Layout = new javax.swing.GroupLayout(asignarSonidoPanel50);
        asignarSonidoPanel50.setLayout(asignarSonidoPanel50Layout);
        asignarSonidoPanel50Layout.setHorizontalGroup(
            asignarSonidoPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asignarSonidoPanel50Layout.setVerticalGroup(
            asignarSonidoPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        numeroDelPadPanel5.setBackground(new java.awt.Color(10, 10, 10));

        numeroDelPad105.setBackground(new java.awt.Color(10, 10, 10));
        numeroDelPad105.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        numeroDelPad105.setForeground(new java.awt.Color(255, 255, 255));
        numeroDelPad105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDelPad105.setText("PAD 5");

        javax.swing.GroupLayout numeroDelPadPanel5Layout = new javax.swing.GroupLayout(numeroDelPadPanel5);
        numeroDelPadPanel5.setLayout(numeroDelPadPanel5Layout);
        numeroDelPadPanel5Layout.setHorizontalGroup(
            numeroDelPadPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        numeroDelPadPanel5Layout.setVerticalGroup(
            numeroDelPadPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pad5.setBackground(new java.awt.Color(51, 51, 51));
        pad5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        pad5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pad5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pad5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pad5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pad5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pad5Layout = new javax.swing.GroupLayout(pad5);
        pad5.setLayout(pad5Layout);
        pad5Layout.setHorizontalGroup(
            pad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pad5Layout.setVerticalGroup(
            pad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estructuraPanel50Layout = new javax.swing.GroupLayout(estructuraPanel50);
        estructuraPanel50.setLayout(estructuraPanel50Layout);
        estructuraPanel50Layout.setHorizontalGroup(
            estructuraPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numeroDelPadPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pad5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        estructuraPanel50Layout.setVerticalGroup(
            estructuraPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel50Layout.createSequentialGroup()
                .addComponent(asignarSonidoPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pad5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDelPadPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        estructuraPanel60.setBackground(new java.awt.Color(10, 10, 10));

        asignarSonidoPanel60.setBackground(new java.awt.Color(51, 51, 51));
        asignarSonidoPanel60.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));

        asignarSonidoTxt106.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        asignarSonidoTxt106.setForeground(new java.awt.Color(255, 255, 255));
        asignarSonidoTxt106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignarSonidoTxt106.setText("Asignar");
        asignarSonidoTxt106.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignarSonidoTxt106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt106MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt106MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignarSonidoTxt106MouseExited(evt);
            }
        });

        javax.swing.GroupLayout asignarSonidoPanel60Layout = new javax.swing.GroupLayout(asignarSonidoPanel60);
        asignarSonidoPanel60.setLayout(asignarSonidoPanel60Layout);
        asignarSonidoPanel60Layout.setHorizontalGroup(
            asignarSonidoPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt106, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asignarSonidoPanel60Layout.setVerticalGroup(
            asignarSonidoPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoTxt106, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        numeroDelPadPanel6.setBackground(new java.awt.Color(10, 10, 10));

        numeroDelPad106.setBackground(new java.awt.Color(10, 10, 10));
        numeroDelPad106.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 12)); // NOI18N
        numeroDelPad106.setForeground(new java.awt.Color(255, 255, 255));
        numeroDelPad106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDelPad106.setText("PAD 6");

        javax.swing.GroupLayout numeroDelPadPanel6Layout = new javax.swing.GroupLayout(numeroDelPadPanel6);
        numeroDelPadPanel6.setLayout(numeroDelPadPanel6Layout);
        numeroDelPadPanel6Layout.setHorizontalGroup(
            numeroDelPadPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad106, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        numeroDelPadPanel6Layout.setVerticalGroup(
            numeroDelPadPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroDelPad106, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pad6.setBackground(new java.awt.Color(51, 51, 51));
        pad6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        pad6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pad6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pad6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pad6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pad6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pad6Layout = new javax.swing.GroupLayout(pad6);
        pad6.setLayout(pad6Layout);
        pad6Layout.setHorizontalGroup(
            pad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pad6Layout.setVerticalGroup(
            pad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estructuraPanel60Layout = new javax.swing.GroupLayout(estructuraPanel60);
        estructuraPanel60.setLayout(estructuraPanel60Layout);
        estructuraPanel60Layout.setHorizontalGroup(
            estructuraPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignarSonidoPanel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numeroDelPadPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pad6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        estructuraPanel60Layout.setVerticalGroup(
            estructuraPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estructuraPanel60Layout.createSequentialGroup()
                .addComponent(asignarSonidoPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pad6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDelPadPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelPADSLayout = new javax.swing.GroupLayout(panelPADS);
        panelPADS.setLayout(panelPADSLayout);
        panelPADSLayout.setHorizontalGroup(
            panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPADSLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estructuraPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estructuraPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 37, Short.MAX_VALUE)
                .addGroup(panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estructuraPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        panelPADSLayout.setVerticalGroup(
            panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPADSLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estructuraPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelPADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estructuraPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estructuraPanel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        bg.add(panelPADS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 490, 460));

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 230, 230));
        jLabel1.setText("<html>Guardar los sonidos de los pads en el perfil seleccionado.<html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 180, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método que contiene la funcionalidad del JFileChooser
    // Método que contiene la funcionalidad del JFileChooser para seleccionar audio de un pad específico
    private void selectAudioFile(int padNumber) {

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de audio (MP3, WAV)", "mp3", "wav"));

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            audioFiles[padNumber - 1] = fileChooser.getSelectedFile();
            System.out.println("Archivo asignado al pad " + padNumber + ": " + audioFiles[padNumber - 1].getName());
        }
    }

    // Método para reproducir el sonido de un pad específico
    private void playAudio(int padNumber) {

        File audioFile = audioFiles[padNumber - 1];
        if (audioFile == null) {
            System.out.println("No se ha asignado un sonido al pad: " + padNumber);
            return;
        }

        try {
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            audioClips[padNumber - 1] = AudioSystem.getClip();
            audioClips[padNumber - 1].open(audioStream);
            audioClips[padNumber - 1].start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al reproducir el audio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void cerrarPestañaTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarPestañaTXTMouseEntered
        panelCerrarPantalla.setBackground(new Color(186, 0, 0));
    }//GEN-LAST:event_cerrarPestañaTXTMouseEntered

    private void cerrarPestañaTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarPestañaTXTMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarPestañaTXTMouseClicked

    private void minimizarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarTXTMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarTXTMouseClicked

    private void minimizarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarTXTMouseEntered
        panelMinimizar.setBackground(new Color(50, 50, 50));
    }//GEN-LAST:event_minimizarTXTMouseEntered

    private void panelCerrarPantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarPantallaMouseClicked

    }//GEN-LAST:event_panelCerrarPantallaMouseClicked

    private void panelCerrarPantallaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarPantallaMouseEntered

    }//GEN-LAST:event_panelCerrarPantallaMouseEntered

    private void panelCerrarPantallaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarPantallaMouseExited

    }//GEN-LAST:event_panelCerrarPantallaMouseExited

    private void cerrarPestañaTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarPestañaTXTMouseExited
        panelCerrarPantalla.setBackground(Color.black);
    }//GEN-LAST:event_cerrarPestañaTXTMouseExited

    private void minimizarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarTXTMouseExited
        panelMinimizar.setBackground(Color.black);
    }//GEN-LAST:event_minimizarTXTMouseExited

    private void asignarSonidoTxt101MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt101MouseEntered
        asignarSonidoPanel1.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_asignarSonidoTxt101MouseEntered

    private void asignarSonidoTxt101MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt101MouseExited
        asignarSonidoPanel1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_asignarSonidoTxt101MouseExited

    private void asignarSonidoTxt101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt101MouseClicked
        selectAudioFile(1);
    }//GEN-LAST:event_asignarSonidoTxt101MouseClicked

    private void pad1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad1MouseClicked
        playAudio(1);
    }//GEN-LAST:event_pad1MouseClicked

    private void pad1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad1MousePressed
        pad1.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_pad1MousePressed

    private void pad1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad1MouseReleased
        pad1.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_pad1MouseReleased

    private void asignarSonidoTxt102MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt102MouseEntered
        asignarSonidoPanel2.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_asignarSonidoTxt102MouseEntered

    private void asignarSonidoTxt102MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt102MouseExited
        asignarSonidoPanel2.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_asignarSonidoTxt102MouseExited

    private void asignarSonidoTxt103MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt103MouseEntered
        asignarSonidoPanel30.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_asignarSonidoTxt103MouseEntered

    private void asignarSonidoTxt103MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt103MouseExited
        asignarSonidoPanel30.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_asignarSonidoTxt103MouseExited

    private void asignarSonidoTxt104MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt104MouseEntered
        asignarSonidoPanel4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_asignarSonidoTxt104MouseEntered

    private void asignarSonidoTxt104MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt104MouseExited
        asignarSonidoPanel4.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_asignarSonidoTxt104MouseExited

    private void asignarSonidoTxt105MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt105MouseEntered
        asignarSonidoPanel50.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_asignarSonidoTxt105MouseEntered

    private void asignarSonidoTxt105MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt105MouseExited
        asignarSonidoPanel50.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_asignarSonidoTxt105MouseExited

    private void asignarSonidoTxt106MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt106MouseEntered
        asignarSonidoPanel60.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_asignarSonidoTxt106MouseEntered

    private void asignarSonidoTxt106MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt106MouseExited
        asignarSonidoPanel60.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_asignarSonidoTxt106MouseExited

    private void asignarSonidoTxt102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt102MouseClicked
        selectAudioFile(2);
    }//GEN-LAST:event_asignarSonidoTxt102MouseClicked

    private void asignarSonidoTxt103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt103MouseClicked
        selectAudioFile(3);
    }//GEN-LAST:event_asignarSonidoTxt103MouseClicked

    private void asignarSonidoTxt104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt104MouseClicked
        selectAudioFile(4);
    }//GEN-LAST:event_asignarSonidoTxt104MouseClicked

    private void asignarSonidoTxt105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt105MouseClicked
        selectAudioFile(5);
    }//GEN-LAST:event_asignarSonidoTxt105MouseClicked

    private void asignarSonidoTxt106MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignarSonidoTxt106MouseClicked
        selectAudioFile(6);
    }//GEN-LAST:event_asignarSonidoTxt106MouseClicked

    private void pad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad2MouseClicked
        playAudio(2);
    }//GEN-LAST:event_pad2MouseClicked

    private void pad3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad3MouseClicked
        playAudio(3);
    }//GEN-LAST:event_pad3MouseClicked

    private void pad4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad4MouseClicked
        playAudio(4);
    }//GEN-LAST:event_pad4MouseClicked

    private void pad5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad5MouseClicked
        playAudio(5);
    }//GEN-LAST:event_pad5MouseClicked

    private void pad6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad6MouseClicked
        playAudio(6);
    }//GEN-LAST:event_pad6MouseClicked

    private void pad2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad2MousePressed
        pad2.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_pad2MousePressed

    private void pad2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad2MouseReleased
        pad2.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_pad2MouseReleased

    private void pad3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad3MousePressed
        pad3.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_pad3MousePressed

    private void pad3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad3MouseReleased
        pad3.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_pad3MouseReleased

    private void pad4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad4MousePressed
        pad4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_pad4MousePressed

    private void pad4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad4MouseReleased
        pad4.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_pad4MouseReleased

    private void pad5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad5MousePressed
        pad5.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_pad5MousePressed

    private void pad5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad5MouseReleased
        pad5.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_pad5MouseReleased

    private void pad6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad6MousePressed
        pad6.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_pad6MousePressed

    private void pad6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pad6MouseReleased
        pad6.setBackground(new Color(60, 60, 60));
    }//GEN-LAST:event_pad6MouseReleased

    
    private void reestablecerPads() {
        audioFiles = new File[NUMBER_OF_PADS];
        for (int i = 0; i < panelPADS.getComponentCount(); i++) {
            JPanel padPanel = (JPanel) panelPADS.getComponent(i);
            padPanel.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        JOptionPane.showMessageDialog(this, "Todos los sonidos han sido reestablecidos.");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SamplerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SamplerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SamplerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SamplerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SamplerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asignarSonidoPanel1;
    private javax.swing.JPanel asignarSonidoPanel2;
    private javax.swing.JPanel asignarSonidoPanel30;
    private javax.swing.JPanel asignarSonidoPanel4;
    private javax.swing.JPanel asignarSonidoPanel50;
    private javax.swing.JPanel asignarSonidoPanel60;
    private javax.swing.JLabel asignarSonidoTxt101;
    private javax.swing.JLabel asignarSonidoTxt102;
    private javax.swing.JLabel asignarSonidoTxt103;
    private javax.swing.JLabel asignarSonidoTxt104;
    private javax.swing.JLabel asignarSonidoTxt105;
    private javax.swing.JLabel asignarSonidoTxt106;
    private javax.swing.JLabel beatlabLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cerrarPestañaTXT;
    private javax.swing.JPanel estructuraPanel1;
    private javax.swing.JPanel estructuraPanel2;
    private javax.swing.JPanel estructuraPanel3;
    private javax.swing.JPanel estructuraPanel4;
    private javax.swing.JPanel estructuraPanel50;
    private javax.swing.JPanel estructuraPanel60;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iconBeatLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_TextoReestablecer;
    private javax.swing.JLabel minimizarTXT;
    private javax.swing.JLabel numeroDelPad101;
    private javax.swing.JLabel numeroDelPad102;
    private javax.swing.JLabel numeroDelPad103;
    private javax.swing.JLabel numeroDelPad104;
    private javax.swing.JLabel numeroDelPad105;
    private javax.swing.JLabel numeroDelPad106;
    private javax.swing.JPanel numeroDelPadPanel1;
    private javax.swing.JPanel numeroDelPadPanel2;
    private javax.swing.JPanel numeroDelPadPanel3;
    private javax.swing.JPanel numeroDelPadPanel4;
    private javax.swing.JPanel numeroDelPadPanel5;
    private javax.swing.JPanel numeroDelPadPanel6;
    private javax.swing.JPanel pad1;
    private javax.swing.JPanel pad2;
    private javax.swing.JPanel pad3;
    private javax.swing.JPanel pad4;
    private javax.swing.JPanel pad5;
    private javax.swing.JPanel pad6;
    private javax.swing.JPanel panelCerrarPantalla;
    private javax.swing.JPanel panelMinimizar;
    private javax.swing.JPanel panelPADS;
    private interfaceSampler.PanelRound panelTextoReestablecer;
    // End of variables declaration//GEN-END:variables
}
